version: '3.8'

services:
  frontend:
    build:
      context: ../../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5000/api

  api:
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/loanease
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ai-service:
    build:
      context: ../../ai-services
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  mongodb_data: